version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 45432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    networks:
      - eggnet
           
  ubuntu:
    image: eggapp
    build: ./
    ports:
      - "50050:50050"
    networks:
      - eggnet
    depends_on:
      - db
networks:
  eggnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1